setA = set({1, 3, 10, 0})
setB = set({2, 7, -4})
blnCheck1 = setA.isdisjoint(setB)
blnCheck2 = setA.issubset(setB)
print(blnCheck1)
print(blnCheck2)
print (blnCheck1 and blnCheck2)
print (blnCheck1 or blnCheck2)
